image: node:latest

stages:
  - build
  - publish

build:
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
  script:
    - yarn install
    - CI=false yarn build

publish:
  stage: publish
  variables:
    NPM_TOKEN: ${NPM_REGISTRY_AUTH_TOKEN}

  script:
    - yarn global add semantic-release @semantic-release/git @semantic-release/gitlab @semantic-release/npm
    - yarn semantic-release
  dependencies:
    - build
  only:
    - master
    - tags
