#!/bin/bash

set -eo pipefail

# --------------------
# 𝘕𝘰𝘵𝘪𝘤𝘦:
#
# 𝘛𝘩𝘦 𝘰𝘴 𝘧𝘶𝘯𝘤𝘵𝘪𝘰𝘯𝘴
# 𝘧𝘰𝘳 𝘥𝘦𝘵𝘦𝘳𝘮𝘪𝘯𝘪𝘯𝘨
# 𝘵𝘩𝘦 𝘤𝘶𝘳𝘳𝘦𝘯𝘵 𝘖𝘚
# --------------------

# --------------------
# Use VAR=$(os)
function os {
  case $(uname) in
    'Linux')
      echo 'Linux'
      ;;
    'FreeBSD')
      echo 'FreeBSD'
      ;;
    'Darwin')
      echo 'Mac'
      ;;
    'SunOS')
      echo 'Solaris'
      ;;
    'AIX') ;;
    *) ;;
  esac
}
